// Generated by CoffeeScript 1.4.0
(function() {
  var Component, JSONParser,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('../component').Component;

  JSONParser = (function(_super) {

    __extends(JSONParser, _super);

    function JSONParser() {
      return JSONParser.__super__.constructor.apply(this, arguments);
    }

    JSONParser.prototype.takes = 'data.string';

    JSONParser.prototype.emits = 'data';

    JSONParser.prototype.take = function(input) {
      return this.emit(JSON.parse(input));
    };

    return JSONParser;

  })(Component);

  module.exports = new JSONParser;

}).call(this);
