// Generated by CoffeeScript 1.4.0
(function() {
  var Pipeline;

  Pipeline = (function() {

    function Pipeline() {
      this.components = [];
    }

    Pipeline.prototype["do"] = function(component) {
      this.takes = component.takes;
      this.components.push(component);
      return this;
    };

    Pipeline.prototype.then = function(component) {
      var prev;
      prev = this.components[this.components.length - 1];
      if (!prev) {
        console.error("cannot call then() without having first called do()");
        return false;
      }
      if (!component.canTakeFrom(prev)) {
        console.error("" + component.__proto__.constructor.name + " can't receive input from " + prev.__proto__.constructor.name);
        return false;
      }
      prev.notify(component);
      this.components.push(component);
      return this;
    };

    Pipeline.prototype.take = function(val) {
      return this.components[0].take(val);
    };

    return Pipeline;

  })();

  exports.Pipeline = Pipeline;

}).call(this);
