// Generated by CoffeeScript 1.4.0
(function() {
  var Component, Logger,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('../component').Component;

  Logger = (function(_super) {

    __extends(Logger, _super);

    function Logger() {
      return Logger.__super__.constructor.apply(this, arguments);
    }

    Logger.prototype.takes = '';

    Logger.prototype.emits = '';

    Logger.prototype.take = function(input) {
      console.log(input);
      return this.emit(input);
    };

    return Logger;

  })(Component);

  module.exports = new Logger;

}).call(this);
