// Generated by CoffeeScript 1.4.0
(function() {
  var Component, Sampler,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('../component').Component;

  Sampler = (function(_super) {

    __extends(Sampler, _super);

    Sampler.prototype.takes = '';

    Sampler.prototype.emits = '';

    function Sampler(rate) {
      this.rate = rate;
    }

    Sampler.prototype.take = function(input) {
      if (Math.random() < this.rate) {
        return this.emit(input);
      }
    };

    return Sampler;

  })(Component);

  module.exports = function(rate) {
    return new Sampler(rate);
  };

}).call(this);
